"""v1 schema"""
from alembic import op
import sqlalchemy as sa

revision = '20f8c309f2c5'
down_revision = None
branch_labels = None
depends_on = None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('author_publisher', sa.String(length=200), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('authority_level', sa.Integer(), nullable=False),
    sa.Column('freshness', sa.Float(), nullable=False),
    sa.Column('topics', sa.JSON(), nullable=False),
    sa.Column('relevance', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('learning_missions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('depth_label', sa.String(length=32), nullable=False),
    sa.Column('hours_per_week', sa.Integer(), nullable=False),
    sa.Column('prior_experience', sa.String(length=32), nullable=False),
    sa.Column('intensity', sa.String(length=32), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_missions_user_id'), 'learning_missions', ['user_id'], unique=False)
    op.create_table('source_references',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_references_entity_id'), 'source_references', ['entity_id'], unique=False)
    op.create_index(op.f('ix_source_references_source_id'), 'source_references', ['source_id'], unique=False)
    op.create_table('courses',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('mission_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('active_version_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['mission_id'], ['learning_missions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mission_id')
    )
    op.create_table('learning_sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('mission_id', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('plan', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['learning_missions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_sessions_mission_id'), 'learning_sessions', ['mission_id'], unique=False)
    op.create_index(op.f('ix_learning_sessions_user_id'), 'learning_sessions', ['user_id'], unique=False)
    op.create_table('course_versions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('course_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=24), nullable=False),
    sa.Column('last_researched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('manifest', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_versions_course_id'), 'course_versions', ['course_id'], unique=False)
    op.create_table('phases',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('course_version_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['course_version_id'], ['course_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phases_course_version_id'), 'phases', ['course_version_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('course_version_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('brief', sa.Text(), nullable=False),
    sa.Column('rubric', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['course_version_id'], ['course_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_course_version_id'), 'projects', ['course_version_id'], unique=False)
    op.create_table('skills',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('course_version_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('classification', sa.String(length=32), nullable=False),
    sa.Column('target_depth', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_version_id'], ['course_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lessons',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('phase_id', sa.String(length=64), nullable=False),
    sa.Column('skill_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['phase_id'], ['phases.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lessons_phase_id'), 'lessons', ['phase_id'], unique=False)
    op.create_index(op.f('ix_lessons_skill_id'), 'lessons', ['skill_id'], unique=False)
    op.create_table('misconceptions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('skill_id', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=240), nullable=False),
    sa.Column('related_prerequisite', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_misconceptions_skill_id'), 'misconceptions', ['skill_id'], unique=False)
    op.create_index(op.f('ix_misconceptions_user_id'), 'misconceptions', ['user_id'], unique=False)
    op.create_table('project_submissions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('artifact_uri', sa.Text(), nullable=True),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_submissions_project_id'), 'project_submissions', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_submissions_user_id'), 'project_submissions', ['user_id'], unique=False)
    op.create_table('review_schedules',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('skill_id', sa.String(length=64), nullable=False),
    sa.Column('interval_index', sa.Integer(), nullable=False),
    sa.Column('review_due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'skill_id')
    )
    op.create_index(op.f('ix_review_schedules_skill_id'), 'review_schedules', ['skill_id'], unique=False)
    op.create_index(op.f('ix_review_schedules_user_id'), 'review_schedules', ['user_id'], unique=False)
    op.create_table('skill_dependencies',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('skill_id', sa.String(length=64), nullable=False),
    sa.Column('prerequisite_skill_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['prerequisite_skill_id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('skill_id', 'prerequisite_skill_id')
    )
    op.create_table('skill_mastery',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('skill_id', sa.String(length=64), nullable=False),
    sa.Column('concept', sa.Float(), nullable=False),
    sa.Column('explanation', sa.Float(), nullable=False),
    sa.Column('implementation', sa.Float(), nullable=False),
    sa.Column('debugging', sa.Float(), nullable=False),
    sa.Column('design', sa.Float(), nullable=False),
    sa.Column('transfer', sa.Float(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('retention_confidence', sa.Float(), nullable=False),
    sa.Column('confidence_calibration', sa.Float(), nullable=False),
    sa.Column('hint_dependency', sa.Float(), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'skill_id')
    )
    op.create_index(op.f('ix_skill_mastery_skill_id'), 'skill_mastery', ['skill_id'], unique=False)
    op.create_index(op.f('ix_skill_mastery_user_id'), 'skill_mastery', ['user_id'], unique=False)
    op.create_table('activities',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('lesson_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_lesson_id'), 'activities', ['lesson_id'], unique=False)
    op.create_table('project_evaluations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('submission_id', sa.String(length=64), nullable=False),
    sa.Column('automated_score', sa.Float(), nullable=False),
    sa.Column('rubric_score', sa.Float(), nullable=False),
    sa.Column('review_score', sa.Float(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['project_submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_evaluations_submission_id'), 'project_evaluations', ['submission_id'], unique=False)
    op.create_table('vivas',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('submission_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['project_submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vivas_submission_id'), 'vivas', ['submission_id'], unique=False)
    op.create_table('assessments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('skill_id', sa.String(length=64), nullable=False),
    sa.Column('activity_id', sa.String(length=64), nullable=True),
    sa.Column('assessment_type', sa.String(length=40), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('difficulty', sa.Float(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('rubric', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_skill_id'), 'assessments', ['skill_id'], unique=False)
    op.create_table('viva_questions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('viva_id', sa.String(length=64), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['viva_id'], ['vivas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_viva_questions_viva_id'), 'viva_questions', ['viva_id'], unique=False)
    op.create_table('assessment_attempts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('assessment_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('answer', sa.JSON(), nullable=False),
    sa.Column('correctness', sa.Float(), nullable=False),
    sa.Column('learner_confidence', sa.Float(), nullable=False),
    sa.Column('hint_level', sa.Integer(), nullable=False),
    sa.Column('independent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_attempts_user_id'), 'assessment_attempts', ['user_id'], unique=False)
    op.create_table('viva_responses',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('question_id', sa.String(length=64), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['viva_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_viva_responses_question_id'), 'viva_responses', ['question_id'], unique=False)
    op.create_table('assessment_evidence',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('attempt_id', sa.String(length=64), nullable=False),
    sa.Column('skill_id', sa.String(length=64), nullable=False),
    sa.Column('dimension', sa.String(length=32), nullable=False),
    sa.Column('assessment_type', sa.String(length=40), nullable=False),
    sa.Column('difficulty', sa.Float(), nullable=False),
    sa.Column('correctness', sa.Float(), nullable=False),
    sa.Column('hint_level', sa.Integer(), nullable=False),
    sa.Column('learner_confidence', sa.Float(), nullable=False),
    sa.Column('independent', sa.Boolean(), nullable=False),
    sa.Column('misconception_detected', sa.String(length=240), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['assessment_attempts.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_evidence_attempt_id'), 'assessment_evidence', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_assessment_evidence_skill_id'), 'assessment_evidence', ['skill_id'], unique=False)
    op.create_table('hint_usage',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('attempt_id', sa.String(length=64), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['assessment_attempts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hint_usage_attempt_id'), 'hint_usage', ['attempt_id'], unique=False)
    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hint_usage_attempt_id'), table_name='hint_usage')
    op.drop_table('hint_usage')
    op.drop_index(op.f('ix_assessment_evidence_skill_id'), table_name='assessment_evidence')
    op.drop_index(op.f('ix_assessment_evidence_attempt_id'), table_name='assessment_evidence')
    op.drop_table('assessment_evidence')
    op.drop_index(op.f('ix_viva_responses_question_id'), table_name='viva_responses')
    op.drop_table('viva_responses')
    op.drop_index(op.f('ix_assessment_attempts_user_id'), table_name='assessment_attempts')
    op.drop_table('assessment_attempts')
    op.drop_index(op.f('ix_viva_questions_viva_id'), table_name='viva_questions')
    op.drop_table('viva_questions')
    op.drop_index(op.f('ix_assessments_skill_id'), table_name='assessments')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_vivas_submission_id'), table_name='vivas')
    op.drop_table('vivas')
    op.drop_index(op.f('ix_project_evaluations_submission_id'), table_name='project_evaluations')
    op.drop_table('project_evaluations')
    op.drop_index(op.f('ix_activities_lesson_id'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_skill_mastery_user_id'), table_name='skill_mastery')
    op.drop_index(op.f('ix_skill_mastery_skill_id'), table_name='skill_mastery')
    op.drop_table('skill_mastery')
    op.drop_table('skill_dependencies')
    op.drop_index(op.f('ix_review_schedules_user_id'), table_name='review_schedules')
    op.drop_index(op.f('ix_review_schedules_skill_id'), table_name='review_schedules')
    op.drop_table('review_schedules')
    op.drop_index(op.f('ix_project_submissions_user_id'), table_name='project_submissions')
    op.drop_index(op.f('ix_project_submissions_project_id'), table_name='project_submissions')
    op.drop_table('project_submissions')
    op.drop_index(op.f('ix_misconceptions_user_id'), table_name='misconceptions')
    op.drop_index(op.f('ix_misconceptions_skill_id'), table_name='misconceptions')
    op.drop_table('misconceptions')
    op.drop_index(op.f('ix_lessons_skill_id'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_phase_id'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_table('skills')
    op.drop_index(op.f('ix_projects_course_version_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_phases_course_version_id'), table_name='phases')
    op.drop_table('phases')
    op.drop_index(op.f('ix_course_versions_course_id'), table_name='course_versions')
    op.drop_table('course_versions')
    op.drop_index(op.f('ix_learning_sessions_user_id'), table_name='learning_sessions')
    op.drop_index(op.f('ix_learning_sessions_mission_id'), table_name='learning_sessions')
    op.drop_table('learning_sessions')
    op.drop_table('courses')
    op.drop_index(op.f('ix_source_references_source_id'), table_name='source_references')
    op.drop_index(op.f('ix_source_references_entity_id'), table_name='source_references')
    op.drop_table('source_references')
    op.drop_index(op.f('ix_learning_missions_user_id'), table_name='learning_missions')
    op.drop_table('learning_missions')
    op.drop_table('users')
    op.drop_table('sources')
    # ### end Alembic commands ###
